### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JellyBrick** [JellyBrick/mpp-frontend#7]
- [x] '현재 접속 중인 플레이어 수' 위치 변경
- [x] 플레이어 이름 디자인 변경
- [x] 채팅 버블 디자인 변경
- [x] 채팅창 크기 변경
- [x] 채팅 블러 적용
- [x] 채팅 애니메이션 적용
- [x] 피아노 위치 조정 (간섭 최소화)
- [x] 방 생성 창 디자인 변경
- [x] 설정 창 디자인 변경
- [x] 채팅 버블 위치 수정
- [x] 채팅 입력창 디자인 수정
- [x] 채팅 입력창 위치 수정
- [x] 툴바 오른쪽에 다 밀어넣기
- [x] 방 선택기 리팩토링
- [x] 노티 디자인 변경
- [x] 애니메이션 추가
 - [x] 플레이어가 연주할때 플레이어 이름에 애니메이션 
- [x] 어두운 테마 스위치
- [x] 깃허브, 페이팔 FAB 구현
